### ISSUE TITLE
Please a a license

### ISSUE THREAD

**Issue by vmx** [GeoHistoricalData/geocoder-api#2]
Is this project open source? If yes, could you please add a license?

**Comment by leny-pa** [comment]
Yes, the geocoder is open-source under the Affero GPL license.
We will add a license file.

**Comment by julienperret** [comment]
We provided a License file here: https://github.com/GeoHistoricalData/geocoder-api/blob/master/LICENSE.txt
Thank you for your attention and vigilance.
https://github.com/GeoHistoricalData/geocoder-api/commit/3b220f1d8239eb7d4821c8876e36dbce8bea667f

**Comment by vmx** [comment]
Thanks! Please note that your package.json still says "Unlicense": https://github.com/GeoHistoricalData/geocoder-api/blob/0e4c533b29749b9272a9c807674704ddcea6c6e4/package.json#L13
